import { ArrowRight, MessageCircle } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Breadcrumbs from '../components/Breadcrumbs'
import ProductCard from '../components/ProductCard'
import Seo from '../components/Seo'
import { getLine } from '../data/lines'
import { getProduct, products } from '../data/products'
import styles from './ProductDetail.module.css'

export default function ProductDetail(){const {slug}=useParams();const product=getProduct(slug);if(!product)return <div className="not-found-inline"><h1>Produto não encontrado</h1><Link className="button" to="/produtos">Voltar ao catálogo</Link></div>;const line=getLine(product.line);const related=products.filter(p=>p.id!==product.id&&(p.line===product.line||p.category===product.category)).slice(0,3);const jsonLd={'@context':'https://schema.org','@type':'Product',name:product.name,description:product.short,brand:{'@type':'Brand',name:'Atual Pet'},category:product.category,image:product.image};return <><Seo title={product.name} description={`${product.short} Conheça indicações e apresentações.`} path={`/produtos/${product.slug}`} image={product.image} jsonLd={jsonLd}/><main className={styles.page}><div className="shell"><Breadcrumbs items={[{label:'Produtos',to:'/produtos'},{label:product.name}]}/><div className={styles.main}><div className={styles.gallery}><img src={product.image} width="760" height="860" alt={product.imagePending?`Imagem pendente para ${product.name}`:`${product.name} — ${line.name}`}/>{product.imagePending&&<span>Imagem oficial pendente</span>}</div><div className={styles.info}><span className="eyebrow">{line.name} · {product.category.replace('-',' ')}</span><h1>{product.name}</h1><p className={styles.lead}>{product.description}</p><dl>{product.dilution&&<div><dt>Diluição</dt><dd>{product.dilution}</dd></div>}{product.volumes.length>0&&<div><dt>Apresentações</dt><dd>{product.volumes.join(' · ')}</dd></div>}{product.fragrance&&<div><dt>Fragrância</dt><dd>{product.fragrance}</dd></div>}</dl><div className="button-row"><Link className="button" to="/onde-encontrar">Onde encontrar <ArrowRight size={16}/></Link><Link className="button button--outline" to="/contato"><MessageCircle size={16}/> Falar com a Atual Pet</Link></div></div></div>
      <div className={styles.details}><section><span className="eyebrow">Aplicação</span><h2>Informações do produto</h2></section><div>{product.indication&&<article><h3>Indicação</h3><p>{product.indication}</p></article>}{product.benefits.length>0&&<article><h3>Benefícios</h3><ul>{product.benefits.map(item=><li key={item}>{item}</li>)}</ul></article>}{product.usage&&<article><h3>Modo de uso</h3><p>{product.usage}</p></article>}{product.notes&&<article><h3>Informação importante</h3><p>{product.notes}</p></article>}</div></div>
      <section className={styles.related}><h2>Você também pode conhecer</h2><div className="product-grid product-grid--three">{related.map(item=><ProductCard key={item.id} product={item}/>)}</div></section></div></main></>}
